# Generated by Django 5.2.7 on 2025-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField()),
                ('fundacion_mascota', models.CharField(max_length=50)),
                ('detalles_adicionales', models.TextField(blank=True)),
                ('foto_mascota', models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/')),
            ],
        ),
    ]
