# Generated by Django 5.2.7 on 2025-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fundacion_mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fundacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
