# Generated by Django 5.2.7 on 2025-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_remove_mascota_fundacion_mascota_mascota_fundacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id_registro',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
