# Generated by Django 5.2.7 on 2025-10-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_remove_mascota_id_registro_mascota_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tamaño_mascota',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
