# Generated by Django 5.2.7 on 2025-10-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_tamaño_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='tamaño_mascota',
            new_name='tamano_mascota',
        ),
    ]
